name: Sanitizers

on:
  - pull_request
  - push

jobs:
  AddressSanitizer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install unrar
      - name: Create and run configure script
        run: |
          export CC=clang
          export CFLAGS="-fsanitize=address -fno-omit-frame-pointer -g"
          export LDFLAGS="$CFLAGS"
          autoconf; ./configure
          (cd test-dev; autoconf; ./configure)
      - name: Build library
        run: make
      - name: Build and run test
        run: make check
      - name: Build and run regression tests
        run: (cd test-dev && make)
  MemorySanitizer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install unrar
      - name: Create and run configure script
        run: |
          export CC=clang
          export CFLAGS="-fsanitize=memory -fsanitize-memory-track-origins=2 -fno-omit-frame-pointer -g"
          export LDFLAGS="$CFLAGS"
          autoconf; ./configure
          (cd test-dev; autoconf; ./configure)
      - name: Build library
        run: make
      - name: Build and run test
        run: make check
      - name: Build and run regression tests
        run: (cd test-dev && make)
